<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Name</name>
   <tag></tag>
   <elementGuidId>3f27f597-0fec-4da4-9933-7d24852f96e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.w-40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sl. No.'])[1]/following::th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Name&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>6f802823-00f1-4a77-8f87-65260fb0f37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-40</value>
      <webElementGuid>31e6a8cb-acfd-42fa-a987-b334eaab76b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>efcc3f17-de95-49e8-ae77-c76e15981995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;main-content&quot;]/div[@class=&quot;content-area-all&quot;]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;row mx-4 p-4 bd-highlight row_vc&quot;]/div[@class=&quot;card col-lg-12 col-md-12 col-sm-12 col-xs-12 m-2 me-0 p-2&quot;]/div[@class=&quot;ms-2 ps-2 crs-detail&quot;]/div[@class=&quot;table-responsive px-4 row_vc&quot;]/table[@class=&quot;table table-bordered table-hover rectext&quot;]/thead[1]/tr[1]/th[@class=&quot;w-40&quot;]</value>
      <webElementGuid>5b9cf97b-f272-41e5-9610-126321d9ee83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sl. No.'])[1]/following::th[1]</value>
      <webElementGuid>b1c664f2-98e7-488f-bb4d-b53d78c99d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[2]/following::th[2]</value>
      <webElementGuid>5b61010a-195e-4615-ac3d-af525c5652f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone/Email'])[1]/preceding::th[1]</value>
      <webElementGuid>9253a53b-f14b-4ca4-b6c7-f45a9750552b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vice-Chancellor'])[2]/preceding::th[2]</value>
      <webElementGuid>cd5a12c7-093e-41fc-8b15-d13909e28b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name']/parent::*</value>
      <webElementGuid>10d03a76-e2d1-4fa4-b2c8-fdf97051a660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>0531adce-4ce4-496b-a360-87c3c1ecbcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>741cb6de-9109-47d8-9a1e-7e9addd728a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
